import type { Category, Product } from "../types";

export const CATEGORIES: Category[] = [
  { id: "electronics", name: "Electronics", emoji: "📱", color: "#e0f0ff" },
  { id: "fashion", name: "Fashion", emoji: "👗", color: "#ffe0f0" },
  { id: "home", name: "Home & Living", emoji: "🏠", color: "#e0ffe8" },
  { id: "sports", name: "Sports", emoji: "⚽", color: "#fff8e0" },
  { id: "beauty", name: "Beauty", emoji: "💄", color: "#f0e0ff" },
  { id: "toys", name: "Toys & Games", emoji: "🎮", color: "#fff0e0" },
  { id: "books", name: "Books", emoji: "📚", color: "#e0e8ff" },
  { id: "grocery", name: "Grocery", emoji: "🛒", color: "#edffd9" },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    description:
      "Industry-leading noise canceling with Auto NC Optimizer. Crystal clear hands-free calling with 4 beamforming microphones. Up to 30-hour battery life with quick charging.",
    price: 27999,
    originalPrice: 34999,
    discountPercent: 20,
    rating: 47,
    reviewCount: 3842,
    images: [
      "https://picsum.photos/seed/prod1/400/400",
      "https://picsum.photos/seed/prod1b/400/400",
      "https://picsum.photos/seed/prod1c/400/400",
    ],
    category: "electronics",
    sellerId: "sony-official",
    inStock: true,
    specs: [
      ["Battery", "30 hours"],
      ["Driver", "30mm"],
      ["Weight", "250g"],
      ["Connectivity", "Bluetooth 5.2"],
    ],
    tags: ["noise-cancelling", "wireless", "premium", "hot"],
  },
  {
    id: 2,
    title: "Apple AirPods Pro 2nd Generation",
    description:
      "Active Noise Cancellation that blocks out the world. Transparency mode lets you hear and stay connected. Adaptive EQ automatically tunes music to your ears.",
    price: 18999,
    originalPrice: 24999,
    discountPercent: 24,
    rating: 48,
    reviewCount: 12650,
    images: [
      "https://picsum.photos/seed/prod2/400/400",
      "https://picsum.photos/seed/prod2b/400/400",
      "https://picsum.photos/seed/prod2c/400/400",
    ],
    category: "electronics",
    sellerId: "apple-authorized",
    inStock: true,
    specs: [
      ["Battery", "6+30 hours"],
      ["Chip", "H2"],
      ["Water Resistance", "IPX4"],
      ["Connectivity", "Bluetooth 5.3"],
    ],
    tags: ["apple", "wireless", "anc", "new"],
  },
  {
    id: 3,
    title: "Samsung Galaxy Watch 6 Classic 47mm",
    description:
      "Track your health with advanced sensors. Physical rotating bezel for intuitive navigation. Sapphire crystal glass and premium stainless steel design.",
    price: 24999,
    originalPrice: 31999,
    discountPercent: 22,
    rating: 45,
    reviewCount: 2187,
    images: [
      "https://picsum.photos/seed/prod3/400/400",
      "https://picsum.photos/seed/prod3b/400/400",
      "https://picsum.photos/seed/prod3c/400/400",
    ],
    category: "electronics",
    sellerId: "samsung-store",
    inStock: true,
    specs: [
      ["Display", "1.5 inch Super AMOLED"],
      ["Battery", "425mAh"],
      ["Water Resistance", "5ATM"],
      ["OS", "Wear OS 4"],
    ],
    tags: ["smartwatch", "samsung", "premium"],
  },
  {
    id: 4,
    title: "JBL Flip 6 Portable Waterproof Bluetooth Speaker",
    description:
      "Powerful JBL Original Pro Sound. 12 hours playtime. IP67 waterproof and dustproof. PartyBoost for multi-speaker connection.",
    price: 8999,
    originalPrice: 12999,
    discountPercent: 31,
    rating: 46,
    reviewCount: 5634,
    images: [
      "https://picsum.photos/seed/prod4/400/400",
      "https://picsum.photos/seed/prod4b/400/400",
      "https://picsum.photos/seed/prod4c/400/400",
    ],
    category: "electronics",
    sellerId: "jbl-official",
    inStock: true,
    specs: [
      ["Battery", "12 hours"],
      ["Power", "30W"],
      ["Water Resistance", "IP67"],
      ["Weight", "550g"],
    ],
    tags: ["portable", "waterproof", "bluetooth", "hot"],
  },
  {
    id: 5,
    title: "Logitech MX Master 3S Wireless Mouse",
    description:
      "8K DPI any-surface tracking. Ultra-fast MagSpeed scrolling. Multi-device control with Easy-Switch button. Ergonomic sculpted shape.",
    price: 7999,
    originalPrice: 9999,
    discountPercent: 20,
    rating: 49,
    reviewCount: 8921,
    images: [
      "https://picsum.photos/seed/prod5/400/400",
      "https://picsum.photos/seed/prod5b/400/400",
      "https://picsum.photos/seed/prod5c/400/400",
    ],
    category: "electronics",
    sellerId: "logitech-store",
    inStock: true,
    specs: [
      ["DPI", "200-8000"],
      ["Battery", "70 days"],
      ["Connectivity", "USB-C/Bluetooth"],
      ["Buttons", "7"],
    ],
    tags: ["productivity", "wireless", "ergonomic"],
  },
  {
    id: 6,
    title: "iPad Air 5th Generation 256GB WiFi",
    description:
      "Supercharged by M1 chip. Liquid Retina display with True Tone. Work, learn, and create like never before. All-day battery life.",
    price: 69999,
    originalPrice: 74999,
    discountPercent: 7,
    rating: 48,
    reviewCount: 4215,
    images: [
      "https://picsum.photos/seed/prod6/400/400",
      "https://picsum.photos/seed/prod6b/400/400",
      "https://picsum.photos/seed/prod6c/400/400",
    ],
    category: "electronics",
    sellerId: "apple-authorized",
    inStock: true,
    specs: [
      ["Chip", "Apple M1"],
      ["Display", "10.9 inch Liquid Retina"],
      ["Storage", "256GB"],
      ["Battery", "10 hours"],
    ],
    tags: ["apple", "tablet", "premium", "new"],
  },
  {
    id: 7,
    title: "Nike Air Max 270 Running Shoes",
    description:
      "Max Air unit in the heel for superior cushioning. Breathable upper mesh for all-day comfort. Iconic 270 design that turns heads everywhere you go.",
    price: 8499,
    originalPrice: 12999,
    discountPercent: 35,
    rating: 44,
    reviewCount: 7823,
    images: [
      "https://picsum.photos/seed/prod7/400/400",
      "https://picsum.photos/seed/prod7b/400/400",
      "https://picsum.photos/seed/prod7c/400/400",
    ],
    category: "fashion",
    sellerId: "nike-official",
    inStock: true,
    specs: [
      ["Material", "Mesh + Synthetic"],
      ["Sole", "Rubber"],
      ["Closure", "Lace-up"],
      ["Type", "Running"],
    ],
    tags: ["nike", "running", "comfortable", "hot"],
  },
  {
    id: 8,
    title: "Levi's 511 Slim Fit Jeans",
    description:
      "Slim through the hip and thigh, straight leg opening. Stretch fabric for all-day comfort and movement. Classic 5-pocket styling.",
    price: 3499,
    originalPrice: 4999,
    discountPercent: 30,
    rating: 43,
    reviewCount: 15432,
    images: [
      "https://picsum.photos/seed/prod8/400/400",
      "https://picsum.photos/seed/prod8b/400/400",
      "https://picsum.photos/seed/prod8c/400/400",
    ],
    category: "fashion",
    sellerId: "levis-store",
    inStock: true,
    specs: [
      ["Fit", "Slim"],
      ["Material", "99% Cotton, 1% Elastane"],
      ["Rise", "Mid"],
      ["Closure", "Zip fly"],
    ],
    tags: ["denim", "casual", "classic"],
  },
  {
    id: 9,
    title: "Adidas Ultraboost 23 Running Shoes",
    description:
      "Responsive BOOST midsole returns energy with every step. Primeknit+ upper wraps your foot in adaptive support. Continental rubber outsole.",
    price: 11999,
    originalPrice: 17999,
    discountPercent: 33,
    rating: 47,
    reviewCount: 6234,
    images: [
      "https://picsum.photos/seed/prod9/400/400",
      "https://picsum.photos/seed/prod9b/400/400",
      "https://picsum.photos/seed/prod9c/400/400",
    ],
    category: "fashion",
    sellerId: "adidas-official",
    inStock: true,
    specs: [
      ["Upper", "Primeknit+"],
      ["Midsole", "BOOST"],
      ["Outsole", "Continental Rubber"],
      ["Drop", "10mm"],
    ],
    tags: ["adidas", "running", "premium"],
  },
  {
    id: 10,
    title: "Dyson V15 Detect Absolute Vacuum",
    description:
      "Laser reveals invisible dust. Automatically adapts suction power. Intelligently optimizes cleaning for the task. Up to 60 minutes of fade-free power.",
    price: 54999,
    originalPrice: 64999,
    discountPercent: 15,
    rating: 48,
    reviewCount: 3921,
    images: [
      "https://picsum.photos/seed/prod10/400/400",
      "https://picsum.photos/seed/prod10b/400/400",
      "https://picsum.photos/seed/prod10c/400/400",
    ],
    category: "home",
    sellerId: "dyson-official",
    inStock: true,
    specs: [
      ["Battery", "60 minutes"],
      ["Bin Volume", "0.77L"],
      ["Weight", "3.1kg"],
      ["Suction", "230AW"],
    ],
    tags: ["dyson", "vacuum", "premium", "new"],
  },
  {
    id: 11,
    title: "Instant Pot Duo 7-in-1 Electric Pressure Cooker 6Qt",
    description:
      "7 appliances in 1: pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker and warmer. 13 customizable programs.",
    price: 6999,
    originalPrice: 9999,
    discountPercent: 30,
    rating: 47,
    reviewCount: 28456,
    images: [
      "https://picsum.photos/seed/prod11/400/400",
      "https://picsum.photos/seed/prod11b/400/400",
      "https://picsum.photos/seed/prod11c/400/400",
    ],
    category: "home",
    sellerId: "instant-pot",
    inStock: true,
    specs: [
      ["Capacity", "6 Quart"],
      ["Programs", "13"],
      ["Safety", "10 mechanisms"],
      ["Voltage", "110V"],
    ],
    tags: ["kitchen", "appliance", "cooking", "hot"],
  },
  {
    id: 12,
    title: "Philips Hue Smart Bulb Starter Kit (4 bulbs)",
    description:
      "Control with your voice using Alexa, Google, or Siri. 16 million colors and warm-to-cool white. Schedule lights and create automations.",
    price: 9499,
    originalPrice: 13999,
    discountPercent: 32,
    rating: 45,
    reviewCount: 11234,
    images: [
      "https://picsum.photos/seed/prod12/400/400",
      "https://picsum.photos/seed/prod12b/400/400",
      "https://picsum.photos/seed/prod12c/400/400",
    ],
    category: "home",
    sellerId: "philips-store",
    inStock: true,
    specs: [
      ["Colors", "16 million"],
      ["Connectivity", "Zigbee/Bluetooth"],
      ["Lumens", "800lm each"],
      ["Lifespan", "25,000 hours"],
    ],
    tags: ["smart-home", "lighting", "alexa"],
  },
  {
    id: 13,
    title: "Yoga Mat Premium Non-Slip 6mm Thick",
    description:
      "Extra thick 6mm for superior cushioning. Non-slip surface for stability in any pose. Eco-friendly TPE material. Comes with carrying strap.",
    price: 1999,
    originalPrice: 3499,
    discountPercent: 43,
    rating: 44,
    reviewCount: 9876,
    images: [
      "https://picsum.photos/seed/prod13/400/400",
      "https://picsum.photos/seed/prod13b/400/400",
      "https://picsum.photos/seed/prod13c/400/400",
    ],
    category: "sports",
    sellerId: "sporty-gear",
    inStock: true,
    specs: [
      ["Thickness", "6mm"],
      ["Material", "TPE"],
      ["Size", "183cm x 61cm"],
      ["Weight", "1.2kg"],
    ],
    tags: ["yoga", "fitness", "eco-friendly"],
  },
  {
    id: 14,
    title: "Resistance Bands Set 11-Piece Exercise Kit",
    description:
      "5 resistance levels from 10-50 lbs. Includes door anchor, ankle straps, and handles. Perfect for home workouts, physical therapy, and strength training.",
    price: 1499,
    originalPrice: 2499,
    discountPercent: 40,
    rating: 43,
    reviewCount: 17832,
    images: [
      "https://picsum.photos/seed/prod14/400/400",
      "https://picsum.photos/seed/prod14b/400/400",
      "https://picsum.photos/seed/prod14c/400/400",
    ],
    category: "sports",
    sellerId: "fit-zone",
    inStock: true,
    specs: [
      ["Resistance", "10-50 lbs"],
      ["Pieces", "11"],
      ["Material", "Natural Latex"],
      ["Usage", "Home/Gym"],
    ],
    tags: ["fitness", "home-workout", "beginner"],
  },
  {
    id: 15,
    title: "L'Oreal Paris Revitalift Triple Power Anti-Aging Serum",
    description:
      "Visibly reduces wrinkles in just 4 weeks. Pro-Retinol, Vitamin C & Hyaluronic Acid triple action formula. Dermatologist tested.",
    price: 2899,
    originalPrice: 4299,
    discountPercent: 33,
    rating: 44,
    reviewCount: 6543,
    images: [
      "https://picsum.photos/seed/prod15/400/400",
      "https://picsum.photos/seed/prod15b/400/400",
      "https://picsum.photos/seed/prod15c/400/400",
    ],
    category: "beauty",
    sellerId: "loreal-official",
    inStock: true,
    specs: [
      ["Volume", "30ml"],
      ["Skin Type", "All"],
      ["Key Ingredients", "Retinol, Vit C, Hyaluronic"],
      ["Usage", "Morning/Night"],
    ],
    tags: ["skincare", "anti-aging", "serum"],
  },
  {
    id: 16,
    title: "Nintendo Switch OLED Model with Neon Blue and Red Joy-Con",
    description:
      "Vivid 7-inch OLED screen. Enhanced audio. 64GB internal storage. Wide adjustable stand. Play at home on TV or take it on the go.",
    price: 34999,
    originalPrice: 39999,
    discountPercent: 13,
    rating: 48,
    reviewCount: 21456,
    images: [
      "https://picsum.photos/seed/prod16/400/400",
      "https://picsum.photos/seed/prod16b/400/400",
      "https://picsum.photos/seed/prod16c/400/400",
    ],
    category: "toys",
    sellerId: "nintendo-store",
    inStock: true,
    specs: [
      ["Display", "7-inch OLED"],
      ["Storage", "64GB"],
      ["Battery", "4.5-9 hours"],
      ["Players", "Up to 8 online"],
    ],
    tags: ["gaming", "nintendo", "portable", "hot"],
  },
  {
    id: 17,
    title: "LEGO Technic Lamborghini Huracán Tecnica 806 Pieces",
    description:
      "An authentic LEGO replica of the Lamborghini Huracán Tecnica. Features V10 engine with moving pistons, aerodynamic body and working steering.",
    price: 5999,
    originalPrice: 7499,
    discountPercent: 20,
    rating: 47,
    reviewCount: 3421,
    images: [
      "https://picsum.photos/seed/prod17/400/400",
      "https://picsum.photos/seed/prod17b/400/400",
      "https://picsum.photos/seed/prod17c/400/400",
    ],
    category: "toys",
    sellerId: "lego-store",
    inStock: true,
    specs: [
      ["Pieces", "806"],
      ["Age", "18+"],
      ["Length", "12 inches"],
      ["Theme", "Technic"],
    ],
    tags: ["lego", "collector", "premium"],
  },
  {
    id: 18,
    title: "Atomic Habits by James Clear — Hardcover",
    description:
      "Tiny Changes, Remarkable Results. The #1 New York Times bestseller. Over 15 million copies sold. Transform your life with habits that stick.",
    price: 899,
    originalPrice: 1499,
    discountPercent: 40,
    rating: 49,
    reviewCount: 89234,
    images: [
      "https://picsum.photos/seed/prod18/400/400",
      "https://picsum.photos/seed/prod18b/400/400",
      "https://picsum.photos/seed/prod18c/400/400",
    ],
    category: "books",
    sellerId: "books-corner",
    inStock: true,
    specs: [
      ["Pages", "320"],
      ["Language", "English"],
      ["Publisher", "Penguin Random House"],
      ["Format", "Hardcover"],
    ],
    tags: ["self-help", "bestseller", "habits"],
  },
  {
    id: 19,
    title: "Anker 65W Nano II Fast Charger with USB-C Cable",
    description:
      "PowerIQ 3.0 Gen2 enables 65W fast charging. ActiveShield safety features. Compact size fits anywhere. Compatible with MacBook, iPhone, Android.",
    price: 2499,
    originalPrice: 3999,
    discountPercent: 38,
    rating: 47,
    reviewCount: 14567,
    images: [
      "https://picsum.photos/seed/prod19/400/400",
      "https://picsum.photos/seed/prod19b/400/400",
      "https://picsum.photos/seed/prod19c/400/400",
    ],
    category: "electronics",
    sellerId: "anker-store",
    inStock: true,
    specs: [
      ["Output", "65W"],
      ["Port", "USB-C"],
      ["Cable Length", "6ft"],
      ["Compatibility", "Universal USB-C"],
    ],
    tags: ["charger", "fast-charging", "anker"],
  },
  {
    id: 20,
    title: "Beats Fit Pro True Wireless Earbuds",
    description:
      "Active Noise Cancelling blocks external noise. Transparency mode lets you hear the world around you. Flexible, secure-fit wingtips stay in place.",
    price: 15999,
    originalPrice: 19999,
    discountPercent: 20,
    rating: 46,
    reviewCount: 7823,
    images: [
      "https://picsum.photos/seed/prod20/400/400",
      "https://picsum.photos/seed/prod20b/400/400",
      "https://picsum.photos/seed/prod20c/400/400",
    ],
    category: "electronics",
    sellerId: "beats-store",
    inStock: true,
    specs: [
      ["Battery", "6+18 hours"],
      ["Chip", "Apple H1"],
      ["Water Resistance", "IPX4"],
      ["Connectivity", "Bluetooth 5.0"],
    ],
    tags: ["beats", "wireless", "anc", "fitness"],
  },
  {
    id: 21,
    title: "Under Armour HOVR Phantom 3 Running Shoes",
    description:
      "UA HOVR technology provides 'zero gravity feel' to maintain energy return. Connected running app tracks your run metrics in real time.",
    price: 9499,
    originalPrice: 14999,
    discountPercent: 37,
    rating: 45,
    reviewCount: 4231,
    images: [
      "https://picsum.photos/seed/prod21/400/400",
      "https://picsum.photos/seed/prod21b/400/400",
      "https://picsum.photos/seed/prod21c/400/400",
    ],
    category: "sports",
    sellerId: "under-armour",
    inStock: true,
    specs: [
      ["Technology", "UA HOVR"],
      ["Upper", "Engineered Mesh"],
      ["Connectivity", "MapMyRun"],
      ["Drop", "8mm"],
    ],
    tags: ["running", "smart", "connected"],
  },
  {
    id: 22,
    title: "Maybelline Fit Me Matte + Poreless Foundation",
    description:
      "Natural coverage that blurs pores and controls shine. Lightweight formula that looks and feels like your skin. Available in 40+ shades.",
    price: 799,
    originalPrice: 1299,
    discountPercent: 38,
    rating: 43,
    reviewCount: 23456,
    images: [
      "https://picsum.photos/seed/prod22/400/400",
      "https://picsum.photos/seed/prod22b/400/400",
      "https://picsum.photos/seed/prod22c/400/400",
    ],
    category: "beauty",
    sellerId: "maybelline-official",
    inStock: true,
    specs: [
      ["Volume", "30ml"],
      ["Coverage", "Medium-Full"],
      ["Finish", "Matte"],
      ["SPF", "No SPF"],
    ],
    tags: ["makeup", "foundation", "affordable"],
  },
  {
    id: 23,
    title: "Xiaomi Redmi Note 13 Pro 5G 256GB",
    description:
      "200MP OIS flagship camera. 5000mAh battery with 67W HyperCharge. 6.67 inch AMOLED 120Hz display. Snapdragon 7s Gen 2 processor.",
    price: 24999,
    originalPrice: 29999,
    discountPercent: 17,
    rating: 44,
    reviewCount: 6789,
    images: [
      "https://picsum.photos/seed/prod23/400/400",
      "https://picsum.photos/seed/prod23b/400/400",
      "https://picsum.photos/seed/prod23c/400/400",
    ],
    category: "electronics",
    sellerId: "xiaomi-store",
    inStock: true,
    specs: [
      ["Camera", "200MP OIS"],
      ["Battery", "5000mAh + 67W"],
      ["Display", '6.67" 120Hz AMOLED'],
      ["Storage", "256GB"],
    ],
    tags: ["smartphone", "5g", "camera", "new"],
  },
  {
    id: 24,
    title: "Nespresso Vertuo Next Coffee Machine",
    description:
      "5 cup sizes from Espresso to Alto. Centrifusion extraction for perfect crema. Bluetooth connected for personalized coffee experiences. Eco-friendly design.",
    price: 13999,
    originalPrice: 18999,
    discountPercent: 26,
    rating: 46,
    reviewCount: 8934,
    images: [
      "https://picsum.photos/seed/prod24/400/400",
      "https://picsum.photos/seed/prod24b/400/400",
      "https://picsum.photos/seed/prod24c/400/400",
    ],
    category: "home",
    sellerId: "nespresso-store",
    inStock: true,
    specs: [
      ["Cup Sizes", "5 (40ml-414ml)"],
      ["Heat Up", "30 seconds"],
      ["Water Tank", "1.1L"],
      ["Connectivity", "Bluetooth"],
    ],
    tags: ["coffee", "kitchen", "smart", "premium"],
  },
  {
    id: 25,
    title: "Garmin Forerunner 255 GPS Running Watch",
    description:
      "Advanced running dynamics with new physiological metrics. Up to 14 days battery life in smartwatch mode. Multi-band GPS for accuracy.",
    price: 22999,
    originalPrice: 27999,
    discountPercent: 18,
    rating: 47,
    reviewCount: 3124,
    images: [
      "https://picsum.photos/seed/prod25/400/400",
      "https://picsum.photos/seed/prod25b/400/400",
      "https://picsum.photos/seed/prod25c/400/400",
    ],
    category: "sports",
    sellerId: "garmin-official",
    inStock: true,
    specs: [
      ["Battery", "14 days"],
      ["GPS", "Multi-band"],
      ["Water Resistance", "5ATM"],
      ["Display", "1.3 inch MIP"],
    ],
    tags: ["running", "gps", "garmin", "fitness"],
  },
];

export const BANNER_SLIDES = [
  {
    id: 1,
    title: "Featured Promotions",
    subtitle: "Up to 40% off premium electronics",
    cta: "Shop Now",
    image: "/assets/generated/hero-banner.dim_800x400.jpg",
    tag: "HOT DEALS",
  },
  {
    id: 2,
    title: "Fashion Flash Sale",
    subtitle: "Top brands at unbeatable prices",
    cta: "Explore",
    image: "/assets/generated/hero-banner.dim_800x400.jpg",
    tag: "LIMITED TIME",
  },
  {
    id: 3,
    title: "New Arrivals This Week",
    subtitle: "Discover the latest trends",
    cta: "Browse",
    image: "/assets/generated/hero-banner.dim_800x400.jpg",
    tag: "NEW",
  },
];

export function getProductById(id: number): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter(
    (p) => p.tags.includes("hot") || p.tags.includes("new"),
  ).slice(0, 8);
}

export function getDiscountedProducts(): Product[] {
  return [...PRODUCTS]
    .sort((a, b) => b.discountPercent - a.discountPercent)
    .slice(0, 12);
}
