/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Order {
  'id' : bigint,
  'status' : string,
  'total' : bigint,
  'createdAt' : Timestamp,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : bigint,
  'title' : string,
  'inStock' : boolean,
  'originalPrice' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'discountPercent' : bigint,
  'specs' : Array<[string, string]>,
  'category' : string,
  'sellerId' : string,
  'rating' : bigint,
  'price' : bigint,
  'reviewCount' : bigint,
  'images' : Array<string>,
}
export interface Review {
  'userId' : UserId,
  'date' : Timestamp,
  'text' : string,
  'productId' : bigint,
  'rating' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'addReview' : ActorMethod<[bigint, bigint, string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'placeOrder' : ActorMethod<[], bigint>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCartQuantity' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];