/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'total' : IDL.Nat,
  'createdAt' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'inStock' : IDL.Bool,
  'originalPrice' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'specs' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'category' : IDL.Text,
  'sellerId' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const UserId = IDL.Principal;
export const Review = IDL.Record({
  'userId' : UserId,
  'date' : Timestamp,
  'text' : IDL.Text,
  'productId' : IDL.Nat,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], []),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], []),
  'placeOrder' : IDL.Func([], [IDL.Nat], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Timestamp = IDL.Int;
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'total' : IDL.Nat,
    'createdAt' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'inStock' : IDL.Bool,
    'originalPrice' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'specs' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'category' : IDL.Text,
    'sellerId' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const UserId = IDL.Principal;
  const Review = IDL.Record({
    'userId' : UserId,
    'date' : Timestamp,
    'text' : IDL.Text,
    'productId' : IDL.Nat,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], []),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], []),
    'placeOrder' : IDL.Func([], [IDL.Nat], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };